switches.main.runController = false;
switches.learner_sw.steps = 10000;
switches.learner_sw.sensoryonly_SA = false;
switches.learner_sw.sensoryonly_bandpass = false;
switches.learner_sw.columnar_WTA = false;
switches.learner_sw.SAfiring_check = false;
switches.learner_sw.sensorySA_update = false;
switches.learner_sw.trace_update = false;
switches.learner_sw.trace_normalise = false;
switches.learner_sw.sensorymotor_bandpass = true;
switches.learner_sw.sensorymotor2SA_update = true;
switches.params.sensory_threshold = 1; % Necessary to adjust these to compensate for different
switches.params.motor_threshold = 1;