function switches = setDefaultSwitches(switches)

switches.main.runLearner = false;
switches.main.runController = false;
switches.main.worldType = 'maze';
switches.main.provide_agent = false;
switches.main.diagonalActions = true;
switches.main.text = 'High';
switches.main.reduced_SA = false;
switches.main.manual_walls = false;
switches.main.load_walls = false;
switches.main.agentGoalPositions = 'random';
switches.main.propagation_noise = false;
switches.main.gatechunk = false;
switches.main.suppressChecks = false;
switches.main.suppressFigures = false;
switches.main.reset_agent = false;
switches.main.xy_sensory = false;

switches.experiment.Verstynen = false;

switches.diagnostic.occupancy_grid = false;
switches.diagnostic.track_SA = false;
switches.diagnostic.track_SA_FORCE = false;
switches.diagnostic.track_sensory = false;
switches.diagnostic.track_firing = false;
switches.diagnostic.clear_firing = false;
switches.diagnostic.decodeSA = false;
switches.diagnostic.decodegate = false;
switches.diagnostic.resultMat = false;
switches.diagnostic.stepsMat = false;
switches.diagnostic.processingMat = false;
switches.diagnostic.total_steps = false;
switches.diagnostic.total_processing = false;
switches.diagnostic.stepsByResult = false;
switches.diagnostic.IT = false;

switches.control_sw.goalIterations = 10;
switches.control_sw.controller_steps = 1000;
switches.control_sw.learn_chunks = false;
switches.control_sw.useMaxPropagate = false;
switches.control_sw.useProbPropagate = false;
switches.control_sw.useRandomTrialDist = false;
switches.control_sw.initial_sensory_firing = false;
switches.control_sw.sensoryreward2SA = false;
switches.control_sw.SAreward_bandpass = false;
switches.control_sw.SAreward_check = 'fatal';
switches.control_sw.use_chunks = false;
switches.control_sw.chunk_activation = false;
switches.control_sw.chunk_trace = false;
switches.control_sw.chunk_synapse_update = false;
switches.control_sw.chunk_normalise = false;
switches.control_sw.propagation = 'deterministic';
switches.control_sw.EIbalance = false;
switches.control_sw.SAthreshold = false;
switches.control_sw.SAdivisive = false;
switches.control_sw.gate_update = false;
switches.control_sw.gate_threshold = false;
switches.control_sw.motor_activate = false;
switches.control_sw.postAction_SA_WTA = false;
switches.control_sw.reset_sensory = false;
switches.control_sw.reset_reward = false;
switches.control_sw.reset_SA = false;
switches.control_sw.reset_motor = false;
switches.control_sw.reset_chunk = false;
switches.control_sw.reset_gate = false;
switches.control_sw.reset_SAtrace = false;
switches.control_sw.stochastic_exploration = false;
switches.control_sw.surprise = false;
switches.control_sw.inhibit_states = false;

switches.learner_sw.steps = 5000;
switches.learner_sw.accelerated_learning = false;
switches.learner_sw.antiHebb = false;
switches.learner_sw.forced_run = false;
switches.learner_sw.initial_sensory_update = false;
switches.learner_sw.sensoryonly_SA = false;
switches.learner_sw.sensoryonly_bandpass = false;
switches.learner_sw.columnar_WTA = false;
switches.learner_sw.SAfiring_check = false;
switches.learner_sw.sensorySA_update = false;
switches.learner_sw.activate_motor = false;
switches.learner_sw.sensorymotor_SA = false;
switches.learner_sw.sensorymotor_bandpass = false;
switches.learner_sw.actionWTA = false;
switches.learner_sw.sensorymotor2SA_update = false;
switches.learner_sw.trace_update = false;
switches.learner_sw.bilateraltrace_update = false;
switches.learner_sw.SASA_Hebb_update = false;
switches.learner_sw.trace_normalise = false;
switches.learner_sw.sensory_gate = false;
switches.learner_sw.columnarWTA_gate = false;
switches.learner_sw.sensorygate_update = false;
switches.learner_sw.sensorySA_gate = false;
switches.learner_sw.gate_bandpass = false;
switches.learner_sw.gateWTA = false;
switches.learner_sw.postBand_sensoryGate_update = false;
switches.learner_sw.SAgate_update = false;
switches.learner_sw.gate_check = false;
switches.learner_sw.gatemotor_update = false;
switches.learner_sw.gatemotor_normalise = false;
switches.learner_sw.test_motor = false;
switches.learner_sw.motor2SA_update = false;
switches.learner_sw.SA2motor_update = false;
switches.learner_sw.motorSA_normalise = false;
switches.learner_sw.getSAtrace = false;
switches.learner_sw.SA_reset = false;
switches.learner_sw.sensory_reset = false;
switches.learner_sw.action_reset = false;

switches.params.sensorytoSA_dilution = 1; %0.3
switches.params.motortoSA_dilution = 1; %0.2
switches.params.SAtomotor_dilution = 1; %0.2
switches.params.chunk_dilution = 1;
switches.params.chunk_weights = 0.1;
switches.params.sensorytogate_dilution = 1;
switches.params.gatetomotor_dilution = 1;
switches.params.SAtogate_dilution = 1;
switches.params.trace_learningRate = 10; %0.1; %0.001; % 0.0001
%switches.params.gate_sparseness = 99;
%switches.params.gate_slope = 1000;
switches.params.gate_inhibition = 0.55;
switches.params.state_noise = 0.01;
switches.params.propagation_noise = 0.01;
switches.params.SAthresholdTop = 1;
switches.params.SAthresholdBottom = 0;
switches.params.motor_inhibition = 0.2;
switches.params.normalisation_threshold = 1;
switches.params.sensory_threshold = 1; % Necessary to adjust these to compensate for different
switches.params.motor_threshold = 0.25; % numbers of synapses to sensory and motor cells.
switches.params.trace_threshold = 4; %0.01
switches.params.sensorytogate_threshold = 0.5;
switches.params.SAtogate_threshold = 0.5;
switches.params.gatechunk_learningRate = 100;
switches.params.gatetogatechunk_threshold = 1;
switches.params.gatechunktogate_threshold = 1;
switches.params.antiHebbFactor = 0.99;
switches.params.learningRate = 100; %100
switches.params.randomTrialDist = 1;
switches.params.eta = 0.0;
switches.params.SAtochunk_learningRate = 10^26;
switches.params.chunktoSA_learningRate = 11; %11 %0.00001 %0.000001; %0.01
switches.params.chunk_modifier = 1.8;
switches.params.chunk_threshold = 1;
switches.params.chunk_eta = 0.5; % 0.3 gives two or three SA in a row. % 0.5 works well for martinet
switches.params.gatebandpass_low = 0.1;
switches.params.gatebandpass_high = 0.95;
switches.params.worldSize_x = 10;
switches.params.worldSize_y = 10;
switches.params.sensorymotorbandpass_low = 0.5;
switches.params.sensorymotorbandpass_high = 1.5;
switches.params.sensoryonlybandpass_low = 0.1;
switches.params.sensoryonlybandpass_high = 0.95;
switches.params.walls = '';
switches.params.startPosition_x = 1;
switches.params.startPosition_y = 1;
switches.params.goalPosition_x = 1;
switches.params.goalPosition_y = 1;
switches.params.agent_to_load = '';
switches.params.inhibited_state = [];
switches.params.divisive_threshold = 0.00001;
end